### ISSUE TITLE
Gif not working

### ISSUE THREAD

**Issue by NewGitHubUser0** [Auth-Xero/DisCrasher#2]
![image](https://user-images.githubusercontent.com/128610313/231091694-159a2b48-09a8-49b3-99fc-c835efa2cc73.png)

**Comment by Auth-Xero** [comment]
0 information provided,
Include stack trace.

**Comment by NewGitHubUser0** [comment]
Thanks for the answer! I used the DisGif feature. I clicked on the upload button, selected the video, and pressed Submit. After that, I need to wait about one minute. After this time, the message "Failed to upload to gfycat!" appears. I tried about 10 times, used different video file sizes, always had to wait about 1 minute and got error.
